/**
 * App state: data that is specific to the application's behavior
 */

// Activity
export const SET_OFFLINE = "SET_OFFLINE";
export const SET_ONLINE = "SET_ONLINE";

// Reconnection
export const SET_SHOULD_RECONNECT = "SET_SHOULD_RECONNECT";

/**
 * Domain data: data that the application needs to show, use, or modify
 */

export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const CLEAR_ACCOUNT = "CLEAR_ACCOUNT";

/**
 * UI data: data related to the views/components display state
 */
export const SHOW_APP_NAVIGATION = "SHOW_APP_NAVIGATION";
export const HIDE_APP_NAVIGATION = "HIDE_APP_NAVIGATION";

export const UPDATE_ACTIVE_SELECTION_AREA = "UPDATE_ACTIVE_SELECTION_AREA";
export const RESET_ACTIVE_SELECTION_AREA = "RESET_ACTIVE_SELECTION_AREA";

export const SET_SELECTION_MDOE_ON = "SET_SELECTION_MODE_ON";
export const SET_SELECTION_MODE_OFF = "SET_SELECTION_MODE_OFF";

export const SET_EDIT_MODE_ON = "SET_EDIT_MODE_ON";
export const SET_EDIT_MODE_OFF = "SET_EDIT_MODE_OFF";

export const UPDATE_FREEZE_COLUMN_COUNT = "UPDATE_FREEZE_COLUMN_COUNT";
export const RESET_FREEZE_COLUMN_COUNT = "RESET_FREEZE_COLUMN_COUNT";

export const UPDATE_FREEZE_ROW_COUNT = "UPDATE_FREEZE_ROW_COUNT";
export const RESET_FREEZE_ROW_COUNT = "RESET_FREEZE_ROW_COUNT";

export const UPDATE_ROW_COUNT = "UPDATE_ROW_COUNT";
export const RESET_ROW_COUNT = "RESET_ROW_COUNT";

export const UPDATE_COLUMN_COUNT = "UPDATE_COLUMN_COUNT";
export const RESET_COLUMN_COUNT = "RESET_COLUMN_COUNT";

export const UPDATE_ACTIVE_SHEET_NAME = "UPDATE_ACTIVE_SHEET_NAME";
export const RESET_ACTIVE_SHEET_NAME = "RESET_ACTIVE_SHEET_NAME";

export const UPDATE_SHEET_NAMES = "UPDATE_SHEET_NAMES";
export const RESET_SHEET_NAMES = "RESET_SHEET_NAMES";

export const UPDATE_SHEET_CELL_DATA = "UPDATE_SHEET_CELL_DATA";
export const RESET_SHEET_CELL_DATA = "RESET_SHEET_CELL_DATA";

export const UPDATE_COLUMN_WIDTHS = "UPDATE_COLUMN_WIDTHS"; 
export const RESET_COLUMN_WIDTHS = "RESET_COLUMN_WIDTHS";

export const UPDATE_ROW_HEIGHTS = "UPDATE_ROW_HEIGHTS";
export const RESET_ROW_HEIGHTS = "RESET_ROW_HEIGHTS";

export const UPDATE_STAGNANT_SELECTION_AREAS = "UPDATE_STAGNANT_SELECTION_AREAS";
export const RESET_STAGNANT_SELECTION_AREAS = "RESET_STAGNANT_SELECTION_AREAS";

export const UPDATE_ACTIVE_CELL_POSITION = "UPDATE_ACTIVE_CELL_POSITION";
export const RESET_ACTIVE_CELL_POSITION = "RESET_ACTIVE_CELL_POSITION";

export const UPDATE_ACTIVE_CELL_SELECTION_AREA_INDEX = "UPDATE_ACTIVE_CELL_SELECTION_AREA_INDEX";
export const RESET_ACTIVE_CELL_SELECTION_AREA_INDEX = "RESET_ACTIVE_CELL_SELECTION_AREA_INDEX";