GET http://localhost:3000/COA_manager/COAGroups

###

# POST http://localhost:3000/designer/COAs HTTP/1.1
# content-type: application/json

# {
#   "reportingPeriod": {
#     "name": "Q1",
#     "startDate": "01/01/2010",
#     "endDate": "06/31/2010",
#     "application": "SRI"
#   }
# }
