GET http://localhost:3000/workflows

# POST http://localhost:3000/designer/statuses HTTP/1.1
# content-type: application/json

# {
#   "status": {
#     "name"        : "sample",
#     "description" : "testing",
#     "isActive"    : false
#   }
# }
