export const DEFAULT_EXCEL_ROWS = 200;
export const DEFAULT_EXCEL_COLUMNS = 26;

export const DEFAULT_EXCEL_ROW_HEIGHT = 25;
export const DEFAULT_EXCEL_COLUMN_WIDTH = 80;

export const DEFAULT_EXCEL_ROW_HEIGHT_HIDDEN = 2;
export const DEFAULT_EXCEL_COLUMN_WIDTH_HIDDEN = 2;

export const DEFAULT_EXCEL_ROW_HEIGHT_HEADER = DEFAULT_EXCEL_ROW_HEIGHT;
export const DEFAULT_EXCEL_COLUMN_WIDTH_HEADER = 40;