export const DEFAULT_EXCEL_ROWS = 200;
export const DEFAULT_EXCEL_COLUMNS = 26;

export const DEFAULT_EXCEL_ROW_HEIGHT = 25;
export const DEFAULT_EXCEL_COLUMN_WIDTH = 100;

export const DEFAULT_EXCEL_ROW_HEIGHT_HIDDEN = 2;
export const DEFAULT_EXCEL_COLUMN_WIDTH_HIDDEN = 2;

export const DEFAULT_EXCEL_ROW_HEIGHT_HEADER = DEFAULT_EXCEL_ROW_HEIGHT;
export const DEFAULT_EXCEL_COLUMN_WIDTH_HEADER = 40;

export const DEFAULT_EXCEL_ACTIVE_SHEET_NAME = "Sheet1";

export const DEFAULT_EXCEL_FREEZE_COLUMN_COUNT = 0;
export const DEFAULT_EXCEL_FREEZE_ROW_COUNT = 0;

export const DEFAULT_EXCEL_ACTIVE_SELECTION_AREA = null;

export const DEFAULT_EXCEL_CELL_ORIGIN_ROW = 1;
export const DEFAULT_EXCEL_CELL_ORIGIN_COLUMN = 1;

export const DEFAULT_EXCEL_SHEET_NAMES = [];
export const DEFAULT_EXCEL_SHEET_CELL_VALUES = [];

export const DEFAULT_EXCEL_COLUMN_WIDTHS = [];
export const DEFAULT_EXCEL_ROW_HEIGHTS = [];

export const DEFAULT_EXCEL_STAGNANT_SELECTION_AREAS = [];

export const DEFAULT_EXCEL_ACTIVE_CELL_POSITION = { 
  x: DEFAULT_EXCEL_CELL_ORIGIN_COLUMN,
  y: DEFAULT_EXCEL_CELL_ORIGIN_ROW
};
