export const ROLE_USER_MANAGER = "USER_MANAGER";
export const ROLE_TEMPLATE_MANAGER = "TEMPLATE_MANAGER";
export const ROLE_BUNDLE_MANAGER = "BUNDLE_MANAGER";
export const ROLE_ORGANIZATION_MANAGER = "ORGANIZATION_MANAGER";
export const ROLE_SECTOR_MANAGER = "SECTOR_MANAGER";

export const ROLES = [
  ROLE_USER_MANAGER,
  ROLE_TEMPLATE_MANAGER,
  ROLE_BUNDLE_MANAGER,
  ROLE_ORGANIZATION_MANAGER,
  ROLE_SECTOR_MANAGER
];

// Levels of role
export const ROLE_LEVEL_ADMIN = "ADMIN";
export const ROLE_LEVEL_LHIN = "LHIN";
export const ROLE_LEVEL_SECTOR = "SECTOR";
export const ROLE_LEVEL_ORGANIZATION = "ORGANIZATION";
export const ROLE_LEVEL_NOT_APPLICABLE = "N/A";

export const ROLE_SCOPES = [ 
  ROLE_LEVEL_ADMIN, 
  // ROLE_LEVEL_LHIN, 
  ROLE_LEVEL_SECTOR,
  ROLE_LEVEL_ORGANIZATION, 
  ROLE_LEVEL_NOT_APPLICABLE 
];