export const ROLE_USER_MANAGER = "USER_MANAGER";
export const ROLE_TEMPLATE_MANAGER = "TEMPLAGE_MANAGER";
export const ROLE_PACKAGE_MANAGER = "PACKAGE_MANAGER"
export const ROLE_ORGANIZATION_MANAGER = "ORGANIZATION_MANAGER";
export const ROLE_SECTOR_MANAGER = "SECTOR_MANAGER";

// Levels of role
export const ROLE_LEVEL_ADMIN = "ADMIN";
export const ROLE_LEVEL_LHIN = "LHIN";
export const ROLE_LEVEL_ORGANIZATION = "ORGANIZATION";
export const ROLE_LEVEL_NOT_APPLICABLE = "N/A";