export const ROLE_USER_MANAGER = "USER_MANAGER";
export const ROLE_TEMPLATE_MANAGER = "TEMPLAGE_MANAGER";
export const ROLE_DATA_MANAGER = "DATA_MANAGER";
export const ROLE_PACKAGE_MANAGER = "PACKAGE_MANAGER"
export const ROLE_ORGANIZATION_MANAGER = "ORGANIZATION_MANAGER";
