export const ONLINE = "online";
export const OFFLINE = "offline";

export const DEFAULT_EXCEL_CELL_ORIGIN_ROW = 1;
export const DEFAULT_EXCEL_CELL_ORIGIN_COLUMN = 1;

export const DEFAULT_EXCEL_CELL_ACTIVE = { row: DEFAULT_EXCEL_CELL_ORIGIN_ROW, column :DEFAULT_EXCEL_CELL_ORIGIN_COLUMN };
export const DEFAULT_EXCEL_SELECTION_AREA = { x1: DEFAULT_EXCEL_CELL_ORIGIN_COLUMN, y1: DEFAULT_EXCEL_CELL_ORIGIN_ROW, x2: DEFAULT_EXCEL_CELL_ORIGIN_COLUMN, y2: DEFAULT_EXCEL_CELL_ORIGIN_ROW };