# GET http://localhost:3000/root/statuses

POST http://localhost:3000/root/statuses HTTP/1.1
content-type: application/json

{
  "status": {
    "name"        : "sample",
    "description" : "testing",
    "isActive"    : false
  }
}