export const ROLE_USER_MANAGER = "USER_MANAGER";
export const ROLE_TEMPLATE_MANAGER = "TEMPLATE_MANAGER";
export const ROLE_BUNDLE_MANAGER = "BUNDLE_MANAGER"
export const ROLE_ORGANIZATION_MANAGER = "ORGANIZATION_MANAGER";
export const ROLE_SECTOR_MANAGER = "SECTOR_MANAGER";

// Levels of role
export const ROLE_LEVEL_ADMIN = "ADMIN";
export const ROLE_LEVEL_SECTOR = "SECTOR";
export const ROLE_LEVEL_LHIN = "LHIN";
export const ROLE_LEVEL_ORGANIZATION = "ORGANIZATION";
export const ROLE_LEVEL_NOT_APPLICABLE = "N/A";